### ISSUE TITLE
Maling trus ngejual barang orang om?

### ISSUE THREAD

**Issue by mozartrafi** [NishimiyaYuzuru/roni#3]

**Comment by H29id** [comment]
Kang maling

**Comment by mozartrafi** [comment]
_Anggap lah lo nyolong barang di alfamart, terus lo jual lagi di perumahan lo, duit haram ga sih itu?_

**Comment by PikaProgram** [comment]
knp gak [dmca aja](https://github.com/github/dmca/)

**Comment by PikaProgram** [comment]
eh abang @mozartrafi sehat bang?

**Comment by mozartrafi** [comment]
Ga guna bocah dikasih gituan, YANG PENTING DUIT DUIT DUIT, bodoamat mah mau haram apa kaga nya

**Comment by hansputera** [comment]
KONTOL NGENTOT BANGSAT ASU JANCOK
